### ISSUE TITLE
how to use debugging?

### ISSUE THREAD

**Issue by tszhang97** [nils-soderman/vscode-motionbuilder-utils#2]
Hi, thanks for your work. Can you give more description on debugging with vscode? how to use "motionbuilder: attach". Thanks a lot.

**Comment by nils-soderman** [comment]
Hi,

Ideally when running the command "MotionBuilder: Attach" VS Code should install any required modules and attach to MotionBuilder automatically.

If you can, please answer the following questions to help me track down the issue:

* Which MotionBuilder version are you using?

* Which Operating System are you using?

* What happens when you run the command, do you receive any messages, popups, anything?

### Some things you could check/try:
1. MotionBuilder's python server needs to be enabled, this should be on by default but you can check by navigating to: **Edit** > **Preferences** > **Python** and under **Python server** make sure **Enabled Server** is checked.

2. The [Python - Microsoft](https://marketplace.visualstudio.com/items?itemName=ms-python.python) VS Code extension _(or an alternative extension which can handle python debugging)_ is also required.

3. [DebugPy](https://pypi.org/project/debugpy/) should be installed automatically if you do not already have that module, however you could try to manually install it, make sure it's importable from MotionBuilder then try to run the attach command.

<br/>

Cheers,  
Nils

**Comment by tszhang97** [comment]
Hi, I'm using win10+MoBu 2020. Shortcut "Ctrl + Enter" works well.
![image](https://user-images.githubusercontent.com/39046939/187117549-646abac3-c312-4036-a243-f236adc8ab5d.png)
This code could generate  a cube in Mobu. However, I don't know how to enter debug mode and could not find where to use  "MotionBuilder: Attach" command. 

Best

**Comment by tszhang97** [comment]
@nils-soderman The main problem is how to attach the vscode to motionbuilder? Is there any tutorial? Thanks.

**Comment by nils-soderman** [comment]
Ah, the "MotionBuilder: Attach" command can be run from the "Show All Commands" _(<kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>P</kbd> by default)_.
Alternatively it can be mapped to a hotkey of your liking in the Keyboard Shortcuts window.

Btw, Just tried on a fresh install of MB 2020, and there seems to be a bug where you might have to run the command "MotionBuilder: Attach" twice the first time you run it, as it'll give a false error message "Failed to install debugpy", but just run the command again and it should hopefully work.

Let me know if that helped!

Cheers,
Nils

**Comment by tszhang97** [comment]
After press 
![image](https://user-images.githubusercontent.com/39046939/187139065-d0c57624-76a1-4aaa-b793-eb974f16a48b.png) and install debugpy sucessfully. Then I press "F5" in vscode to start debugging and the error shows "ModuleNotFoundError: No module named 'pyfbsdk'". The auto-completion works well, should I change the python interpreter? @nils-soderman

**Comment by nils-soderman** [comment]
Try running "MotionBuilder: Attach" a second time, <kbd>F5</kbd>is VS Code's native debug command and will most likely try to debug the file as a standalone .py file.

After MotionBuilder has been attached to VS Code, use <kbd>Ctrl</kbd> + <kbd>Enter</kbd> to execute code and you should see any breakpoints or exceptions trigger.

**Comment by tszhang97** [comment]
Cool, now it's working for me. I tried to close all the MoBu windows and open a new window and attach successfully.  If I open several projects, could I choose which one to attach?

**Comment by nils-soderman** [comment]
Alright, sweet! Worth noting that the MotionBuilder window cannot be minimized when running the attach command.

As of right now choosing which MotionBuilder instance to attach to is not supported, might look into it in the future, but I doubt it's even doable.

**Comment by tszhang97** [comment]
Thanks again for you amazing work!
