### ISSUE TITLE
hi！I'm having some issues with this plugin

### ISSUE THREAD

**Issue by idjjk** [nils-soderman/vscode-motionbuilder-utils#4]
I'm using motionbuilder2023, but I can't link plugins, and when I print in vscdoe and press ctrl enter, motionbuilder2023 doesn't respond at all

**Comment by nils-soderman** [comment]
Hi,

What happens if you run the command manually, without using the shortcut? Just thinking some other extension you have may already be using <kbd>Ctrl</kbd> + <kbd>Enter</kbd>.

So try using <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>P</kbd> and then search for "**MotionBuilder: Execute**" _(must be in a Python file)_.

Also, do look through all of the troubleshooting steps on this page:
[Failed to connect to MotionBuilder [Troubleshooting]](https://github.com/nils-soderman/vscode-motionbuilder-utils/wiki/Failed-to-connect-to-MotionBuilder-%5BTroubleshooting%5D)

Cheers,
Nils

**Comment by idjjk** [comment]
I'm very glad to hear from you. I found that when I try to run a lightweight script, the plugin can run. I think it may be my script's problem that it didn't work before. Thanks again for your generous answer.




1040151318
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nils-soderman/vscode-motionbuilder-utils"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月8日(星期四) 凌晨4:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nils-soderman/vscode-motionbuilder-utils] hi！I'm having some issues with this plugin (Issue #4)





 
Hi,
 
What happens if you run the command manually, without using the shortcut? Just thinking some other extension you have may already be using Ctrl + Enter.
 
So try using Ctrl + Shift + P and then search for "MotionBuilder: Execute" (must be in a Python file).
 
Also, do look through all of the troubleshooting steps on this page:
 Failed to connect to MotionBuilder [Troubleshooting]
 
Cheers,
 Nils

**Comment by nils-soderman** [comment]
Glad to hear it's working, do let me know if you run into any other issues while using this!
